### ISSUE TITLE
READMEのリンク誤りについて

### ISSUE THREAD

**Issue by takayoshi-makabe** [fkubota/kaggler-slack-emoji#2]
READMEに記載されていおります、以下のlinkが二つとも同じものになっているようです！

--- 以下引用

1. emoji を用意
	- 原則、emojiファイル名は `日本語禁止` とします。
	- 作成したい場合は以下のサイトとか使えます。
		- [シンプル](https://emoji-gen.ninja/)
		- [ちょっとこだわりたい](https://emoji-gen.ninja/)

**Comment by fkubota** [comment]
@spider-man-tm 
お、これもありがとうございます！
助かります。
これも対応します！

**Comment by takayoshi-makabe** [comment]
個人的にはこのサイトとかも結構いい感じな気がします 笑

https://zk-phi.github.io/MEGAMOJI/

**Comment by fkubota** [comment]
@spider-man-tm   
まさにそれでしたw

**Comment by fkubota** [comment]
訂正しました！

https://github.com/fkubota/kaggler-slack-emoji/commit/0d9809212938fd2ee48857f36b4bbdb13e66527a
